"""Initial schema: users and sessions

Revision ID: 50aa89e1532b
Revises: 
Create Date: 2026-02-11 01:45:20.324289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50aa89e1532b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.DateTime(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('cookie', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('session_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_user_sessions_access_token'), 'user_sessions', ['access_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_cookie'), 'user_sessions', ['cookie'], unique=True)
    op.create_index(op.f('ix_user_sessions_expiry'), 'user_sessions', ['expiry'], unique=False)
    op.create_index(op.f('ix_user_sessions_fingerprint'), 'user_sessions', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('users_profiles',
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('devices', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('actived_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(op.f('ix_users_profiles_email'), 'users_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_users_profiles_phone'), 'users_profiles', ['phone'], unique=True)
    op.create_index(op.f('ix_users_profiles_username'), 'users_profiles', ['username'], unique=True)
    op.drop_index(op.f('ix_hourly_metric_hour_start'), table_name='hourly_metric_aggregation')
    op.drop_index(op.f('ix_hourly_metric_service'), table_name='hourly_metric_aggregation')
    op.drop_index(op.f('ix_hourly_metric_service_hour'), table_name='hourly_metric_aggregation')
    op.drop_table('hourly_metric_aggregation')
    op.drop_index(op.f('ix_suspicious_remote_ip'), table_name='suspicious_activity')
    op.drop_index(op.f('ix_suspicious_remote_ip_timestamp'), table_name='suspicious_activity')
    op.drop_index(op.f('ix_suspicious_severity'), table_name='suspicious_activity')
    op.drop_index(op.f('ix_suspicious_timestamp'), table_name='suspicious_activity')
    op.drop_table('suspicious_activity')
    op.drop_index(op.f('ix_rate_limit_remote_ip'), table_name='rate_limit_violation')
    op.drop_index(op.f('ix_rate_limit_remote_ip_timestamp'), table_name='rate_limit_violation')
    op.drop_index(op.f('ix_rate_limit_service'), table_name='rate_limit_violation')
    op.drop_index(op.f('ix_rate_limit_timestamp'), table_name='rate_limit_violation')
    op.drop_table('rate_limit_violation')
    op.drop_index(op.f('ix_health_timestamp'), table_name='system_health_snapshot')
    op.drop_table('system_health_snapshot')
    op.drop_index(op.f('ix_metric_snapshot_rate_limited'), table_name='metric_snapshot')
    op.drop_index(op.f('ix_metric_snapshot_remote_ip'), table_name='metric_snapshot')
    op.drop_index(op.f('ix_metric_snapshot_remote_ip_timestamp'), table_name='metric_snapshot')
    op.drop_index(op.f('ix_metric_snapshot_service'), table_name='metric_snapshot')
    op.drop_index(op.f('ix_metric_snapshot_service_timestamp'), table_name='metric_snapshot')
    op.drop_index(op.f('ix_metric_snapshot_timestamp'), table_name='metric_snapshot')
    op.drop_index(op.f('ix_metric_snapshot_user_id'), table_name='metric_snapshot')
    op.drop_table('metric_snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_snapshot',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('remote_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate_limited', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('nginx_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('backend_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('metric_snapshot_pkey'))
    )
    op.create_index(op.f('ix_metric_snapshot_user_id'), 'metric_snapshot', ['user_id'], unique=False)
    op.create_index(op.f('ix_metric_snapshot_timestamp'), 'metric_snapshot', ['timestamp'], unique=False)
    op.create_index(op.f('ix_metric_snapshot_service_timestamp'), 'metric_snapshot', ['service', 'timestamp'], unique=False)
    op.create_index(op.f('ix_metric_snapshot_service'), 'metric_snapshot', ['service'], unique=False)
    op.create_index(op.f('ix_metric_snapshot_remote_ip_timestamp'), 'metric_snapshot', ['remote_ip', 'timestamp'], unique=False)
    op.create_index(op.f('ix_metric_snapshot_remote_ip'), 'metric_snapshot', ['remote_ip'], unique=False)
    op.create_index(op.f('ix_metric_snapshot_rate_limited'), 'metric_snapshot', ['rate_limited'], unique=False)
    op.create_table('system_health_snapshot',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('db_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('db_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('redis_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('redis_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('crypto_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_health_snapshot_pkey'))
    )
    op.create_index(op.f('ix_health_timestamp'), 'system_health_snapshot', ['timestamp'], unique=False)
    op.create_table('rate_limit_violation',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('remote_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('violation_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rate_limit_violation_pkey'))
    )
    op.create_index(op.f('ix_rate_limit_timestamp'), 'rate_limit_violation', ['timestamp'], unique=False)
    op.create_index(op.f('ix_rate_limit_service'), 'rate_limit_violation', ['service'], unique=False)
    op.create_index(op.f('ix_rate_limit_remote_ip_timestamp'), 'rate_limit_violation', ['remote_ip', 'timestamp'], unique=False)
    op.create_index(op.f('ix_rate_limit_remote_ip'), 'rate_limit_violation', ['remote_ip'], unique=False)
    op.create_table('suspicious_activity',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('remote_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('activity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('suspicious_activity_pkey'))
    )
    op.create_index(op.f('ix_suspicious_timestamp'), 'suspicious_activity', ['timestamp'], unique=False)
    op.create_index(op.f('ix_suspicious_severity'), 'suspicious_activity', ['severity'], unique=False)
    op.create_index(op.f('ix_suspicious_remote_ip_timestamp'), 'suspicious_activity', ['remote_ip', 'timestamp'], unique=False)
    op.create_index(op.f('ix_suspicious_remote_ip'), 'suspicious_activity', ['remote_ip'], unique=False)
    op.create_table('hourly_metric_aggregation',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('hour_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('service', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_requests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('successful_requests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_errors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('server_errors', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate_limited_requests', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('avg_nginx_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('avg_backend_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p95_nginx_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p95_backend_latency_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unique_ips', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('hourly_metric_aggregation_pkey')),
    sa.UniqueConstraint('hour_start', 'service', name=op.f('uq_hourly_metric_hour_service'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_hourly_metric_service_hour'), 'hourly_metric_aggregation', ['service', 'hour_start'], unique=False)
    op.create_index(op.f('ix_hourly_metric_service'), 'hourly_metric_aggregation', ['service'], unique=False)
    op.create_index(op.f('ix_hourly_metric_hour_start'), 'hourly_metric_aggregation', ['hour_start'], unique=False)
    op.drop_index(op.f('ix_users_profiles_username'), table_name='users_profiles')
    op.drop_index(op.f('ix_users_profiles_phone'), table_name='users_profiles')
    op.drop_index(op.f('ix_users_profiles_email'), table_name='users_profiles')
    op.drop_table('users_profiles')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_fingerprint'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expiry'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_cookie'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_access_token'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
