"""initial schema with monitoring tables

Revision ID: 38ce6b744b86
Revises: 
Create Date: 2026-02-05 01:32:06.430137

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '38ce6b744b86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hourly_metric_aggregation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hour_start', sa.DateTime(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('client_errors', sa.Integer(), nullable=False),
    sa.Column('server_errors', sa.Integer(), nullable=False),
    sa.Column('rate_limited_requests', sa.Integer(), nullable=False),
    sa.Column('avg_nginx_latency_ms', sa.Float(), nullable=False),
    sa.Column('avg_backend_latency_ms', sa.Float(), nullable=False),
    sa.Column('p95_nginx_latency_ms', sa.Float(), nullable=False),
    sa.Column('p95_backend_latency_ms', sa.Float(), nullable=False),
    sa.Column('unique_ips', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hour_start', 'service', name='uq_hourly_metric_hour_service')
    )
    op.create_index('ix_hourly_metric_hour_start', 'hourly_metric_aggregation', ['hour_start'], unique=False)
    op.create_index('ix_hourly_metric_service', 'hourly_metric_aggregation', ['service'], unique=False)
    op.create_index('ix_hourly_metric_service_hour', 'hourly_metric_aggregation', ['service', 'hour_start'], unique=False)
    op.create_table('metric_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('remote_ip', sa.String(length=45), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('rate_limited', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('nginx_latency_ms', sa.Float(), nullable=False),
    sa.Column('backend_latency_ms', sa.Float(), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_snapshot_rate_limited', 'metric_snapshot', ['rate_limited'], unique=False)
    op.create_index('ix_metric_snapshot_remote_ip', 'metric_snapshot', ['remote_ip'], unique=False)
    op.create_index('ix_metric_snapshot_remote_ip_timestamp', 'metric_snapshot', ['remote_ip', 'timestamp'], unique=False)
    op.create_index('ix_metric_snapshot_service', 'metric_snapshot', ['service'], unique=False)
    op.create_index('ix_metric_snapshot_service_timestamp', 'metric_snapshot', ['service', 'timestamp'], unique=False)
    op.create_index('ix_metric_snapshot_timestamp', 'metric_snapshot', ['timestamp'], unique=False)
    op.create_index('ix_metric_snapshot_user_id', 'metric_snapshot', ['user_id'], unique=False)
    op.create_table('rate_limit_violation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('remote_ip', sa.String(length=45), nullable=False),
    sa.Column('violation_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rate_limit_remote_ip', 'rate_limit_violation', ['remote_ip'], unique=False)
    op.create_index('ix_rate_limit_remote_ip_timestamp', 'rate_limit_violation', ['remote_ip', 'timestamp'], unique=False)
    op.create_index('ix_rate_limit_service', 'rate_limit_violation', ['service'], unique=False)
    op.create_index('ix_rate_limit_timestamp', 'rate_limit_violation', ['timestamp'], unique=False)
    op.create_table('suspicious_activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('remote_ip', sa.String(length=45), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_suspicious_remote_ip', 'suspicious_activity', ['remote_ip'], unique=False)
    op.create_index('ix_suspicious_remote_ip_timestamp', 'suspicious_activity', ['remote_ip', 'timestamp'], unique=False)
    op.create_index('ix_suspicious_severity', 'suspicious_activity', ['severity'], unique=False)
    op.create_index('ix_suspicious_timestamp', 'suspicious_activity', ['timestamp'], unique=False)
    op.create_table('system_health_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('db_status', sa.String(length=20), nullable=False),
    sa.Column('db_latency_ms', sa.Float(), nullable=False),
    sa.Column('redis_status', sa.String(length=20), nullable=False),
    sa.Column('redis_latency_ms', sa.Float(), nullable=False),
    sa.Column('crypto_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_timestamp', 'system_health_snapshot', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_timestamp', table_name='system_health_snapshot')
    op.drop_table('system_health_snapshot')
    op.drop_index('ix_suspicious_timestamp', table_name='suspicious_activity')
    op.drop_index('ix_suspicious_severity', table_name='suspicious_activity')
    op.drop_index('ix_suspicious_remote_ip_timestamp', table_name='suspicious_activity')
    op.drop_index('ix_suspicious_remote_ip', table_name='suspicious_activity')
    op.drop_table('suspicious_activity')
    op.drop_index('ix_rate_limit_timestamp', table_name='rate_limit_violation')
    op.drop_index('ix_rate_limit_service', table_name='rate_limit_violation')
    op.drop_index('ix_rate_limit_remote_ip_timestamp', table_name='rate_limit_violation')
    op.drop_index('ix_rate_limit_remote_ip', table_name='rate_limit_violation')
    op.drop_table('rate_limit_violation')
    op.drop_index('ix_metric_snapshot_user_id', table_name='metric_snapshot')
    op.drop_index('ix_metric_snapshot_timestamp', table_name='metric_snapshot')
    op.drop_index('ix_metric_snapshot_service_timestamp', table_name='metric_snapshot')
    op.drop_index('ix_metric_snapshot_service', table_name='metric_snapshot')
    op.drop_index('ix_metric_snapshot_remote_ip_timestamp', table_name='metric_snapshot')
    op.drop_index('ix_metric_snapshot_remote_ip', table_name='metric_snapshot')
    op.drop_index('ix_metric_snapshot_rate_limited', table_name='metric_snapshot')
    op.drop_table('metric_snapshot')
    op.drop_index('ix_hourly_metric_service_hour', table_name='hourly_metric_aggregation')
    op.drop_index('ix_hourly_metric_service', table_name='hourly_metric_aggregation')
    op.drop_index('ix_hourly_metric_hour_start', table_name='hourly_metric_aggregation')
    op.drop_table('hourly_metric_aggregation')
    # ### end Alembic commands ###
